### ISSUE TITLE
re-active GitHub pages site

### ISSUE THREAD

**Issue by maelle** [poissonconsulting/poissontemplate#1]
@joethorley @aylapear could one of you please reactivate the GitHub pages site for this repository?

- Go to Settings
- Go to Pages
- Source has to be "Deploy from a branch"
- Branch has to be "gh-pages"

![image](https://github.com/user-attachments/assets/a60f67c2-42b6-49ae-beb8-df4c030a1564)

Then could you please change the link in the repo info? (top right of the repo view, see below)

![image](https://github.com/user-attachments/assets/7a0d712e-c702-44ed-b036-b45b8c02ceca)

Thank you!

**Comment by joethorley** [comment]
Done - I just needed to update the link.

**Comment by maelle** [comment]
Awesome, thank you!
